### PR TITLE
History fixes

### PR DESCRIPTION
**Pull request by lucyktan**
@hne3 For the demo... you can click on food names in /food results and /history to show all nutrient values, even though the names don't look clickable.

### CODE REVIEW

**Comment by hne3** [comment]
Getting some weird error messages on this build. Will investigate before merging

**Comment by 12wrigja** [comment]
If you post the errors here as screenshots I can help you debug those.

**Comment by lucyktan** [comment]
Maybe it's rating because it was added to the user history table

**Comment by hne3** [comment]
They're unit test errors, and you can find them all in the Travis build log.

**Pull request merged**
